// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/types/proto/messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseKind int32

const (
	ResponseKind_RESPONSE_KIND_UNSPECIFIED ResponseKind = 0
	ResponseKind_RESPONSE_KIND_NORMAL      ResponseKind = 1
	ResponseKind_RESPONSE_KIND_STREAM      ResponseKind = 2
)

// Enum value maps for ResponseKind.
var (
	ResponseKind_name = map[int32]string{
		0: "RESPONSE_KIND_UNSPECIFIED",
		1: "RESPONSE_KIND_NORMAL",
		2: "RESPONSE_KIND_STREAM",
	}
	ResponseKind_value = map[string]int32{
		"RESPONSE_KIND_UNSPECIFIED": 0,
		"RESPONSE_KIND_NORMAL":      1,
		"RESPONSE_KIND_STREAM":      2,
	}
)

func (x ResponseKind) Enum() *ResponseKind {
	p := new(ResponseKind)
	*p = x
	return p
}

func (x ResponseKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_types_proto_messages_proto_enumTypes[0].Descriptor()
}

func (ResponseKind) Type() protoreflect.EnumType {
	return &file_internal_types_proto_messages_proto_enumTypes[0]
}

func (x ResponseKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseKind.Descriptor instead.
func (ResponseKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{0}
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	OwnedBy       string                 `protobuf:"bytes,4,opt,name=owned_by,json=ownedBy,proto3" json:"owned_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ModelInfo) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ModelInfo) GetOwnedBy() string {
	if x != nil {
		return x.OwnedBy
	}
	return ""
}

type ModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Data          []*ModelInfo           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsResponse) Reset() {
	*x = ModelsResponse{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsResponse) ProtoMessage() {}

func (x *ModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsResponse.ProtoReflect.Descriptor instead.
func (*ModelsResponse) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ModelsResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ModelsResponse) GetData() []*ModelInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClientRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Models        []*ModelInfo           `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Semver        string                 `protobuf:"bytes,4,opt,name=semver,proto3" json:"semver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRegistration) Reset() {
	*x = ClientRegistration{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegistration) ProtoMessage() {}

func (x *ClientRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegistration.ProtoReflect.Descriptor instead.
func (*ClientRegistration) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ClientRegistration) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientRegistration) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ClientRegistration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientRegistration) GetSemver() string {
	if x != nil {
		return x.Semver
	}
	return ""
}

type HeaderEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderEntry) Reset() {
	*x = HeaderEntry{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderEntry) ProtoMessage() {}

func (x *HeaderEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderEntry.ProtoReflect.Descriptor instead.
func (*HeaderEntry) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *HeaderEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeaderEntry) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	Header        []*HeaderEntry         `protobuf:"bytes,6,rep,name=header,proto3" json:"header,omitempty"`
	Body          []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ForwardRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ForwardRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ForwardRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ForwardRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ForwardRequest) GetHeader() []*HeaderEntry {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ForwardRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Header        []*HeaderEntry         `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Kind          ResponseKind           `protobuf:"varint,5,opt,name=kind,proto3,enum=synapse.types.ResponseKind" json:"kind,omitempty"`
	Done          bool                   `protobuf:"varint,6,opt,name=done,proto3" json:"done,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ForwardResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ForwardResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ForwardResponse) GetHeader() []*HeaderEntry {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ForwardResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ForwardResponse) GetKind() ResponseKind {
	if x != nil {
		return x.Kind
	}
	return ResponseKind_RESPONSE_KIND_UNSPECIFIED
}

func (x *ForwardResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ForwardResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ModelProcessingStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ModelId             string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	AverageProcessingMs float64                `protobuf:"fixed64,2,opt,name=average_processing_ms,json=averageProcessingMs,proto3" json:"average_processing_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModelProcessingStats) Reset() {
	*x = ModelProcessingStats{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelProcessingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelProcessingStats) ProtoMessage() {}

func (x *ModelProcessingStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelProcessingStats.ProtoReflect.Descriptor instead.
func (*ModelProcessingStats) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ModelProcessingStats) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelProcessingStats) GetAverageProcessingMs() float64 {
	if x != nil {
		return x.AverageProcessingMs
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Timestamp     int64                   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Processing    []*ModelProcessingStats `protobuf:"bytes,2,rep,name=processing,proto3" json:"processing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetProcessing() []*ModelProcessingStats {
	if x != nil {
		return x.Processing
	}
	return nil
}

type ModelUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Models        []*ModelInfo           `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelUpdateRequest) Reset() {
	*x = ModelUpdateRequest{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUpdateRequest) ProtoMessage() {}

func (x *ModelUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUpdateRequest.ProtoReflect.Descriptor instead.
func (*ModelUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ModelUpdateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ModelUpdateRequest) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{9}
}

func (x *UnregisterRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ForceShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceShutdownRequest) Reset() {
	*x = ForceShutdownRequest{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceShutdownRequest) ProtoMessage() {}

func (x *ForceShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceShutdownRequest.ProtoReflect.Descriptor instead.
func (*ForceShutdownRequest) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ForceShutdownRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{11}
}

type ClientClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientClose) Reset() {
	*x = ClientClose{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientClose) ProtoMessage() {}

func (x *ClientClose) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientClose.ProtoReflect.Descriptor instead.
func (*ClientClose) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ClientClose) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_ForwardRequest
	//	*ServerMessage_ClientClose
	//	*ServerMessage_Pong
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{13}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetForwardRequest() *ForwardRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ForwardRequest); ok {
			return x.ForwardRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetClientClose() *ClientClose {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ClientClose); ok {
			return x.ClientClose
		}
	}
	return nil
}

func (x *ServerMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_ForwardRequest struct {
	ForwardRequest *ForwardRequest `protobuf:"bytes,1,opt,name=forward_request,json=forwardRequest,proto3,oneof"`
}

type ServerMessage_ClientClose struct {
	ClientClose *ClientClose `protobuf:"bytes,2,opt,name=client_close,json=clientClose,proto3,oneof"`
}

type ServerMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

func (*ServerMessage_ForwardRequest) isServerMessage_Message() {}

func (*ServerMessage_ClientClose) isServerMessage_Message() {}

func (*ServerMessage_Pong) isServerMessage_Message() {}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientMessage_Registration
	//	*ClientMessage_ForwardResponse
	//	*ClientMessage_Heartbeat
	//	*ClientMessage_ModelUpdate
	//	*ClientMessage_Unregister
	//	*ClientMessage_ForceShutdown
	Message       isClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_internal_types_proto_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_types_proto_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_internal_types_proto_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ClientMessage) GetMessage() isClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientMessage) GetRegistration() *ClientRegistration {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *ClientMessage) GetForwardResponse() *ForwardResponse {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_ForwardResponse); ok {
			return x.ForwardResponse
		}
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientMessage) GetModelUpdate() *ModelUpdateRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_ModelUpdate); ok {
			return x.ModelUpdate
		}
	}
	return nil
}

func (x *ClientMessage) GetUnregister() *UnregisterRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Unregister); ok {
			return x.Unregister
		}
	}
	return nil
}

func (x *ClientMessage) GetForceShutdown() *ForceShutdownRequest {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_ForceShutdown); ok {
			return x.ForceShutdown
		}
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_Registration struct {
	Registration *ClientRegistration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type ClientMessage_ForwardResponse struct {
	ForwardResponse *ForwardResponse `protobuf:"bytes,2,opt,name=forward_response,json=forwardResponse,proto3,oneof"`
}

type ClientMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type ClientMessage_ModelUpdate struct {
	ModelUpdate *ModelUpdateRequest `protobuf:"bytes,4,opt,name=model_update,json=modelUpdate,proto3,oneof"`
}

type ClientMessage_Unregister struct {
	Unregister *UnregisterRequest `protobuf:"bytes,5,opt,name=unregister,proto3,oneof"`
}

type ClientMessage_ForceShutdown struct {
	ForceShutdown *ForceShutdownRequest `protobuf:"bytes,6,opt,name=force_shutdown,json=forceShutdown,proto3,oneof"`
}

func (*ClientMessage_Registration) isClientMessage_Message() {}

func (*ClientMessage_ForwardResponse) isClientMessage_Message() {}

func (*ClientMessage_Heartbeat) isClientMessage_Message() {}

func (*ClientMessage_ModelUpdate) isClientMessage_Message() {}

func (*ClientMessage_Unregister) isClientMessage_Message() {}

func (*ClientMessage_ForceShutdown) isClientMessage_Message() {}

var File_internal_types_proto_messages_proto protoreflect.FileDescriptor

const file_internal_types_proto_messages_proto_rawDesc = "" +
	"\n" +
	"#internal/types/proto/messages.proto\x12\rsynapse.types\"h\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x19\n" +
	"\bowned_by\x18\x04 \x01(\tR\aownedBy\"V\n" +
	"\x0eModelsResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12,\n" +
	"\x04data\x18\x02 \x03(\v2\x18.synapse.types.ModelInfoR\x04data\"\x95\x01\n" +
	"\x12ClientRegistration\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x120\n" +
	"\x06models\x18\x02 \x03(\v2\x18.synapse.types.ModelInfoR\x06models\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06semver\x18\x04 \x01(\tR\x06semver\"7\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\xcf\x01\n" +
	"\x0eForwardRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x122\n" +
	"\x06header\x18\x06 \x03(\v2\x1a.synapse.types.HeaderEntryR\x06header\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\"\xfc\x01\n" +
	"\x0fForwardResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x122\n" +
	"\x06header\x18\x03 \x03(\v2\x1a.synapse.types.HeaderEntryR\x06header\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12/\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x1b.synapse.types.ResponseKindR\x04kind\x12\x12\n" +
	"\x04done\x18\x06 \x01(\bR\x04done\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"e\n" +
	"\x14ModelProcessingStats\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x122\n" +
	"\x15average_processing_ms\x18\x02 \x01(\x01R\x13averageProcessingMs\"n\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12C\n" +
	"\n" +
	"processing\x18\x02 \x03(\v2#.synapse.types.ModelProcessingStatsR\n" +
	"processing\"c\n" +
	"\x12ModelUpdateRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x120\n" +
	"\x06models\x18\x02 \x03(\v2\x18.synapse.types.ModelInfoR\x06models\"0\n" +
	"\x11UnregisterRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"3\n" +
	"\x14ForceShutdownRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\x06\n" +
	"\x04Pong\",\n" +
	"\vClientClose\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xd0\x01\n" +
	"\rServerMessage\x12H\n" +
	"\x0fforward_request\x18\x01 \x01(\v2\x1d.synapse.types.ForwardRequestH\x00R\x0eforwardRequest\x12?\n" +
	"\fclient_close\x18\x02 \x01(\v2\x1a.synapse.types.ClientCloseH\x00R\vclientClose\x12)\n" +
	"\x04pong\x18\x03 \x01(\v2\x13.synapse.types.PongH\x00R\x04pongB\t\n" +
	"\amessage\"\xc4\x03\n" +
	"\rClientMessage\x12G\n" +
	"\fregistration\x18\x01 \x01(\v2!.synapse.types.ClientRegistrationH\x00R\fregistration\x12K\n" +
	"\x10forward_response\x18\x02 \x01(\v2\x1e.synapse.types.ForwardResponseH\x00R\x0fforwardResponse\x128\n" +
	"\theartbeat\x18\x03 \x01(\v2\x18.synapse.types.HeartbeatH\x00R\theartbeat\x12F\n" +
	"\fmodel_update\x18\x04 \x01(\v2!.synapse.types.ModelUpdateRequestH\x00R\vmodelUpdate\x12B\n" +
	"\n" +
	"unregister\x18\x05 \x01(\v2 .synapse.types.UnregisterRequestH\x00R\n" +
	"unregister\x12L\n" +
	"\x0eforce_shutdown\x18\x06 \x01(\v2#.synapse.types.ForceShutdownRequestH\x00R\rforceShutdownB\t\n" +
	"\amessage*a\n" +
	"\fResponseKind\x12\x1d\n" +
	"\x19RESPONSE_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RESPONSE_KIND_NORMAL\x10\x01\x12\x18\n" +
	"\x14RESPONSE_KIND_STREAM\x10\x02B.Z,github.com/zeyugao/synapse/internal/types/pbb\x06proto3"

var (
	file_internal_types_proto_messages_proto_rawDescOnce sync.Once
	file_internal_types_proto_messages_proto_rawDescData []byte
)

func file_internal_types_proto_messages_proto_rawDescGZIP() []byte {
	file_internal_types_proto_messages_proto_rawDescOnce.Do(func() {
		file_internal_types_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_types_proto_messages_proto_rawDesc), len(file_internal_types_proto_messages_proto_rawDesc)))
	})
	return file_internal_types_proto_messages_proto_rawDescData
}

var file_internal_types_proto_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_types_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_types_proto_messages_proto_goTypes = []any{
	(ResponseKind)(0),            // 0: synapse.types.ResponseKind
	(*ModelInfo)(nil),            // 1: synapse.types.ModelInfo
	(*ModelsResponse)(nil),       // 2: synapse.types.ModelsResponse
	(*ClientRegistration)(nil),   // 3: synapse.types.ClientRegistration
	(*HeaderEntry)(nil),          // 4: synapse.types.HeaderEntry
	(*ForwardRequest)(nil),       // 5: synapse.types.ForwardRequest
	(*ForwardResponse)(nil),      // 6: synapse.types.ForwardResponse
	(*ModelProcessingStats)(nil), // 7: synapse.types.ModelProcessingStats
	(*Heartbeat)(nil),            // 8: synapse.types.Heartbeat
	(*ModelUpdateRequest)(nil),   // 9: synapse.types.ModelUpdateRequest
	(*UnregisterRequest)(nil),    // 10: synapse.types.UnregisterRequest
	(*ForceShutdownRequest)(nil), // 11: synapse.types.ForceShutdownRequest
	(*Pong)(nil),                 // 12: synapse.types.Pong
	(*ClientClose)(nil),          // 13: synapse.types.ClientClose
	(*ServerMessage)(nil),        // 14: synapse.types.ServerMessage
	(*ClientMessage)(nil),        // 15: synapse.types.ClientMessage
}
var file_internal_types_proto_messages_proto_depIdxs = []int32{
	1,  // 0: synapse.types.ModelsResponse.data:type_name -> synapse.types.ModelInfo
	1,  // 1: synapse.types.ClientRegistration.models:type_name -> synapse.types.ModelInfo
	4,  // 2: synapse.types.ForwardRequest.header:type_name -> synapse.types.HeaderEntry
	4,  // 3: synapse.types.ForwardResponse.header:type_name -> synapse.types.HeaderEntry
	0,  // 4: synapse.types.ForwardResponse.kind:type_name -> synapse.types.ResponseKind
	7,  // 5: synapse.types.Heartbeat.processing:type_name -> synapse.types.ModelProcessingStats
	1,  // 6: synapse.types.ModelUpdateRequest.models:type_name -> synapse.types.ModelInfo
	5,  // 7: synapse.types.ServerMessage.forward_request:type_name -> synapse.types.ForwardRequest
	13, // 8: synapse.types.ServerMessage.client_close:type_name -> synapse.types.ClientClose
	12, // 9: synapse.types.ServerMessage.pong:type_name -> synapse.types.Pong
	3,  // 10: synapse.types.ClientMessage.registration:type_name -> synapse.types.ClientRegistration
	6,  // 11: synapse.types.ClientMessage.forward_response:type_name -> synapse.types.ForwardResponse
	8,  // 12: synapse.types.ClientMessage.heartbeat:type_name -> synapse.types.Heartbeat
	9,  // 13: synapse.types.ClientMessage.model_update:type_name -> synapse.types.ModelUpdateRequest
	10, // 14: synapse.types.ClientMessage.unregister:type_name -> synapse.types.UnregisterRequest
	11, // 15: synapse.types.ClientMessage.force_shutdown:type_name -> synapse.types.ForceShutdownRequest
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_types_proto_messages_proto_init() }
func file_internal_types_proto_messages_proto_init() {
	if File_internal_types_proto_messages_proto != nil {
		return
	}
	file_internal_types_proto_messages_proto_msgTypes[13].OneofWrappers = []any{
		(*ServerMessage_ForwardRequest)(nil),
		(*ServerMessage_ClientClose)(nil),
		(*ServerMessage_Pong)(nil),
	}
	file_internal_types_proto_messages_proto_msgTypes[14].OneofWrappers = []any{
		(*ClientMessage_Registration)(nil),
		(*ClientMessage_ForwardResponse)(nil),
		(*ClientMessage_Heartbeat)(nil),
		(*ClientMessage_ModelUpdate)(nil),
		(*ClientMessage_Unregister)(nil),
		(*ClientMessage_ForceShutdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_types_proto_messages_proto_rawDesc), len(file_internal_types_proto_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_types_proto_messages_proto_goTypes,
		DependencyIndexes: file_internal_types_proto_messages_proto_depIdxs,
		EnumInfos:         file_internal_types_proto_messages_proto_enumTypes,
		MessageInfos:      file_internal_types_proto_messages_proto_msgTypes,
	}.Build()
	File_internal_types_proto_messages_proto = out.File
	file_internal_types_proto_messages_proto_goTypes = nil
	file_internal_types_proto_messages_proto_depIdxs = nil
}
